### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by Sid-Bhatia-0**
Address [https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/151](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/151)

### CODE REVIEW

**Comment by Sid-Bhatia-0** [comment]
@findmyway What about the failed checks in the Julia nightly version?

**Comment by findmyway** [comment]
TBH, I don't know...

Watching this issue: https://github.com/actions/runner/issues/2347

**Comment by Sid-Bhatia-0** [comment]
What if we remove the test on Julia-nightly for now, and add an issue to track it? Otherwise, the unpleasant ❌ symbol would show up every time even when the package works correctly on the latest Julia `1.x`.

All the PRs showing an overall ❌  isn't providing any useful information about CI and one will have to go inside every time and look at individual checks to get the relevant information, that is, whether this package works on latest Julia `1.x` or not.

We can always add the nightly check later as and when needed.

**Comment by findmyway** [comment]
Agree.

**Comment by Sid-Bhatia-0** [comment]
Ok. I'll make a PR.

**Pull request merged**
