### PR TITLE
added StopAfterNoImprovement.

### PR DESCRIPTION
**Pull request by norci**

### CODE REVIEW

**Comment by norci** [comment]
This is for issue https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/157

**Comment by findmyway** [comment]
Hi @norci , I think the idea of this stop condition is great!

Your current implementation is restricted to measuring reward only. I'm wondering if we could make it more general. For example, stop when loss no longer decreases.

A draft proposal in my mind is that, we have a function to record some measurement we are interested in and put it into a  circular buffer. Once it's filled we compare and decide whether to stop or not.

Any idea?

**Comment by norci** [comment]
@findmyway ,
Thanks for your advise.
I have used a closure to get the measured value. so this can be used for more general purpose now.

**Comment by findmyway** [comment]
Could you fix the test error first?

**Comment by norci** [comment]
done. the bug was in the test case.
are we ready to merge?

**Pull request merged**
