### PR TITLE
refactor.

### PR DESCRIPTION
**Pull request by norci**
I think the update trajectory code should be encapsulated, and put it in trajectory.jl.

BTW, maybe this small function will be useful
```julia
length(t::AbstractTrajectory) = [size(t[k], ndims(t[k])) for k in keys(t)]
```

### CODE REVIEW

**Comment by findmyway** [comment]
Hi @norci ,

It's a good idea to move the code of updating trajectory into a separate file. But my hunch is that it may increase unnecessary complexity to create a new method of `update!(traj, stage; kwargs...)`. On one hand, `push!` and `pop!` are already enough to describe their behavior. On the other hand, with a new `trajectory`, people still have to extend `update!(traj, policy, env, stage)` since necessary info are only provided by `kwargs` here.

> length(t::AbstractTrajectory) = [size(t[k], ndims(t[k])) for k in keys(t)]

The semantic of `length` here varies based on different kinds of trajectories. But it basically means the number of transitions. So in most cases, it acts like a vector, which should return a `Int` instead of a vector of `Int`:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/767d95eea5c5776673d85453311b8c4fe3333e28/src/policies/agents/trajectories/trajectory.jl#L234-L243

**Comment by norci** [comment]
I agree.
what about this version? only removed a few duplicate code, make the code easier to read.

**Comment by findmyway** [comment]
👍

By the way, this pr and the previous one inspired me to improve the code further for readability. I have an idea to decouple `(agent::AbstractPolicy)(::PreActStage, env::AbstractEnv)` and `(agent::AbstractPolicy)(env::AbstractEnv)`. Will improve this PR later tonight.

**Comment by findmyway** [comment]
Closed in favor of https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/pull/195
Thanks again for your suggestions!

**Pull request closed without merging**
